### PR TITLE
Add a performance test and benchmarks for getting items

### PR DESCRIPTION
**Pull request by alexgleith**
**Related Issue(s):** none

**Description:**

I'm trying to optimise performance in a tool that uses the client and wanted to benchmark the item retrieval.

**PR Checklist:**

- [x] Code is formatted
- [x] Tests pass
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac-api-client/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by matthewhanson** [comment]
Thanks @alexgleith , the tests are only failing due to formatting.  We need to make it clear in the docs in the development section that you need to run `scripts/format`, otherwise it won't pass the formatting linter.   Can you run that and push?

**Comment by matthewhanson** [comment]
actually, run `scripts/test` as that runs everything and there's some other formatting checks in there

**Comment by alexgleith** [comment]
Ok, fixed. FYI, there's a test failing, which I `xfail`ed, because I don't want to mess with it on your behalf. I can fix if you want...

**Comment by matthewhanson** [comment]
Not sure about these latest failures - I just merged the other PR which was big, but shouldn't have affected this.  Can you merge the latest main and gives the tests a run to see if they work locally?

**Comment by alexgleith** [comment]
Cool, should be fixed now @matthewhanson

**Pull request merged**
