### PR TITLE
Remove default limit

### PR DESCRIPTION
**Pull request by gadomski**
**Related Issue(s):** 

- **pystac-client**'s default limit was causing too-large responses in Earth Search: https://github.com/Element84/earth-search/issues/17#issuecomment-1703207616

**Description:**

We should trust the server to know how many things it wants to respond with. Tagging in a couple of folks for reviews since this is changing default behavior. I _don't_ think this is worth marking as a breaking change (thereby forcing a v0.8), but happy to be convinced otherwise.

**PR Checklist:**

- [x] Code is formatted
- [x] Tests pass
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac-api-client/blob/main/CHANGELOG.md)

### CODE REVIEW

**Review by jsignell — APPROVED** [review]
Yeah I like this. That limit always seemed weird to me

**Comment by TomAugspurger** [comment]
@gadomski can you share a bit more (here or in the docs) about how this changes the behavior (maybe depending on how the sever is behaving w.r.t. `limit`)?

> We should trust the server to know how many things it wants to respond with.

Is that part of the response body to `/search`, or just some configuration value on the server?

**Comment by gadomski** [comment]
> @gadomski can you share a bit more (here or in the docs) about how this changes the behavior (maybe depending on how the sever is behaving w.r.t. limit)?

Sure ... this PR changes behavior so that **pystac-client**, by default, does _not_ send a `limit`. The rationale is that the server (presumably) has been tuned to use a reasonable page size by default, and the client shouldn't presume to know better.

> Is that part of the response body to /search, or just some configuration value on the server?

Configuration in the server, e.g. for **stac-fastapi** it's 10: https://github.com/stac-utils/stac-fastapi/blob/main/stac_fastapi/types/stac_fastapi/types/search.py#L125

**Comment by TomAugspurger** [comment]
Ok, thanks. Looks like on the Planetary Computer, we have it set to 250:

```python
❯ curl --silent "https://planetarycomputer.microsoft.com/api/stac/v1/search" | jq '.features | length'
250
```

Following the guidance of the server (by default) makes sense to me.

**Review by TomAugspurger — APPROVED** [review]

**Pull request merged**
