### PR TITLE
Release v0.6.0

### PR DESCRIPTION
**Pull request by gadomski**
Release notes:

```
Added:

- Python 3.11 support [#347](https://github.com/stac-utils/pystac-client/pull/347)
- `request_modifier` to `StacApiIO` to allow for additional authentication mechanisms (e.g. AWS SigV4) [#372](https://github.com/stac-utils/pystac-client/pull/372)
- *Authentication* tutorial, demonstrating how to use to the provided hooks to use both basic and AWS SigV4 authentication [#372](https://github.com/stac-utils/pystac-client/pull/372)
- CI checks for Windows and MacOS [#378](https://github.com/stac-utils/pystac-client/pull/378)
- Fallback to `STAC API - Item Search` when finding a single item in `CollectionClient` if `STAC API - Features` is not implemented [#379](https://github.com/stac-utils/pystac-client/pull/379)

Fixed:

- Stop iteration on an empty page [#338](https://github.com/stac-utils/pystac-client/pull/338)
- Some mishandled cases for datetime intervals [#363](https://github.com/stac-utils/pystac-client/pull/363)
- Collection requests when the Client's url ends in a '/' [#373](https://github.com/stac-utils/pystac-client/pull/373), [#405](https://github.com/stac-utils/pystac-client/pull/405)
- Parse datetimes more strictly [#364](https://github.com/stac-utils/pystac-client/pull/364)

Removed:

- Python 3.7 support [#347](https://github.com/stac-utils/pystac-client/pull/347)
```

**PR Checklist:**

- [x] Code is formatted
- [x] Tests pass
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac-api-client/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by pjhartzell** [comment]
I think there is a missing `item = ` assignment in `collection_client.py` from #379:
https://github.com/stac-utils/pystac-client/blob/c8e2ef381cbf4ff52e1aefe907cb3d35bd38340c/pystac_client/collection_client.py#L172-L173

**Review by pjhartzell — CHANGES_REQUESTED** [review]
I think there is a missing `item = ` assignment in `collection_client.py` from #379:
https://github.com/stac-utils/pystac-client/blob/c8e2ef381cbf4ff52e1aefe907cb3d35bd38340c/pystac_client/collection_client.py#L172-L173

**Review by pjhartzell — APPROVED** [review]
Approved, pending question about dropping Python 3.7 in this minor release.

**Comment by philvarner** [comment]
> @philvarner Per your comment a few months ago [about dropping Python 3.7](https://github.com/stac-utils/pystac-client/pull/347#issuecomment-1315582306), what are your thoughts about including the drop in this _minor_ release?

I think It would be better just to do a 0.6.0 release rather than put it in a < 1.0.0 patch/minor release.

**Comment by gadomski** [comment]
PR updated to v0.6.0, and I've updated our milestones as well to reflect the bump: https://github.com/stac-utils/pystac-client/milestones.

**Review by philvarner — APPROVED** [review]

**Pull request merged**
